common: &common
  adapter: postgresql
  username: scott
  password:  # from psql setup, see Postgresql

development:
  <<: *common
  database: shared-bin_development

test:
  <<: *common
  database: shared-bin_test

production:
  <<: *common
  database: shared-bin_production